services:
  app:
    image: node:18.15.0-alpine
    container_name: app-builder
    user: root  # Run as root to install packages
    working_dir: /app
    volumes:
      - .:/app
    environment:
      - PATH=/app/node_modules/.bin:$PATH
    command:
      - sh
      - -c
      - |
        apk add --no-cache yarn
        yarn config set unsafe-perm true
        yarn install --silent
        yarn run build

  nginx:
    image: nginx:1.23.4-alpine
    container_name: app-nginx
    depends_on:
      - app
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./dist:/usr/share/nginx/html
    ports:
      - "3000:3000"